### ISSUE TITLE
Where is close button?

### ISSUE THREAD

**Issue by noscript** [mkitt/tabline.vim#2]
I wish there would be a close button from the default tabline. Thanks!

**Comment by jimafisk** [comment]
Wrapping PR #4 in a conditional like this:
```
  if (exists("g:tablineclosebutton"))
    let s .= '%=%999XX'
  endif
```
Allows you to put the following line in your `~/.vimrc` to make the close button appear:
`let g:tablineclosebutton=1`

I'd personally like to have the close button to help make vim more accessible to newcomers. Thanks for the plugin and the patch! Looks great!
